package com.example.myapplication

data class AppStrings(
    val searchPlaceholder: String,
    val addToFavorites: String,
    val inFavorites: String,
    val details: String,
    val home: String,
    val map: String,
    val favorites: String,
    val settings: String,
    val updatedAt: String,
    val wind: String,
    val humidity: String,
    val pressure: String,
    val sunrise: String,
    val sunset: String,
    val openOnMap: String,
    val addNote: String,
    val editNote: String,
    val open: String,
    val delete: String,
    val save: String,
    val cancel: String,
    val noteLabel: String,
    val notePlaceholder: String,
    val language: String,
    val russian: String,
    val english: String,
    val theme: String,
    val light: String,
    val dark: String,
    val about: String,
    val weatherData: String,
    val openDetails: String,
    val noFavorites: String,
    val detailedInformation: String,
    val sevenDayForecast: String,
    val version: String,
    val updated: String,
    val offlineWeatherHint: String,
    val setAsHomeCity: String,
    val mapSearchPlaceholder: String,
    val mapSearchResultHint: String,
    val mapYandexKeysSection: String,
    val mapKeysBuiltinName: String,
    val mapKeysAdd: String,
    val mapKeysMakeActive: String,
    val mapKeysRemove: String,
    val mapKeyNameLabel: String,
    val mapKeyValueLabel: String,
    val mapKeysStateActive: String
)

val stringsRu = AppStrings(
    searchPlaceholder = "Поиск города",
    addToFavorites = "Добавить в избранное",
    inFavorites = "В избранном",
    details = "Подробнее",
    home = "Домой",
    map = "Карта",
    favorites = "Избранное",
    settings = "Настройки",
    updatedAt = "Обновлено",
    wind = "Ветер",
    humidity = "Влажность",
    pressure = "Давление",
    sunrise = "Восход",
    sunset = "Закат",
    openOnMap = "Открыть на карте",
    addNote = "Добавить заметку",
    editNote = "Редактировать заметку",
    open = "Открыть",
    delete = "Удалить",
    save = "Сохранить",
    cancel = "Отмена",
    noteLabel = "Заметка",
    notePlaceholder = "Введите заметку...",
    language = "Язык",
    russian = "Русский",
    english = "Английский",
    theme = "Тема",
    light = "Светлая",
    dark = "Тёмная",
    about = "О приложении",
    weatherData = "Данные погоды — Open-Meteo",
    openDetails = "Перейти в детали",
    noFavorites = "Нет избранных городов",
    detailedInformation = "Подробная информация",
    sevenDayForecast = "7-дневный прогноз",
    version = "Версия: 1.0.0",
    updated = "Обновлено: 19.02.2026",
    offlineWeatherHint = "Нет сети — показаны данные без обновления",
    setAsHomeCity = "Сделать домашним",
    mapSearchPlaceholder = "Поиск на карте",
    mapSearchResultHint = "Нажмите «Сделать домашним», чтобы показывать погоду этого города на главном экране.",
    mapYandexKeysSection = "Ключи Яндекс.Карт",
    mapKeysBuiltinName = "Встроенный (учебный)",
    mapKeysAdd = "Добавить ключ",
    mapKeysMakeActive = "Активировать",
    mapKeysRemove = "Удалить",
    mapKeyNameLabel = "Название",
    mapKeyValueLabel = "Ключ API",
    mapKeysStateActive = "Активен"
)

val stringsEn = AppStrings(
    searchPlaceholder = "Search city",
    addToFavorites = "Add to favorites",
    inFavorites = "In favorites",
    details = "Details",
    home = "Home",
    map = "Map",
    favorites = "Favorites",
    settings = "Settings",
    updatedAt = "Updated at",
    wind = "Wind",
    humidity = "Humidity",
    pressure = "Pressure",
    sunrise = "Sunrise",
    sunset = "Sunset",
    openOnMap = "Open on map",
    addNote = "Add note",
    editNote = "Edit note",
    open = "Open",
    delete = "Delete",
    save = "Save",
    cancel = "Cancel",
    noteLabel = "Note",
    notePlaceholder = "Enter note...",
    language = "Language",
    russian = "Russian",
    english = "English",
    theme = "Theme",
    light = "Light",
    dark = "Dark",
    about = "About",
    weatherData = "Weather data — Open-Meteo",
    openDetails = "Open details",
    noFavorites = "No favorite cities",
    detailedInformation = "Detailed Information",
    sevenDayForecast = "7-day forecast",
    version = "Version: 1.0.0",
    updated = "Updated: 19.02.2026",
    offlineWeatherHint = "Offline — showing cached placeholder data",
    setAsHomeCity = "Set as home city",
    mapSearchPlaceholder = "Search on map",
    mapSearchResultHint = "Tap «Set as home city» to show this city’s weather on the home screen.",
    mapYandexKeysSection = "Yandex Map API keys",
    mapKeysBuiltinName = "Built-in (educational)",
    mapKeysAdd = "Add key",
    mapKeysMakeActive = "Activate",
    mapKeysRemove = "Remove",
    mapKeyNameLabel = "Name",
    mapKeyValueLabel = "API key",
    mapKeysStateActive = "Active"
)

fun strings(language: AppLanguage): AppStrings {
    return if (language == AppLanguage.RU) stringsRu else stringsEn
}
