package com.example.myapplication

data class AppStrings(
    val searchPlaceholder: String,
    val addToFavorites: String,
    val inFavorites: String,
    val details: String,
    val home: String,
    val map: String,
    val favorites: String,
    val settings: String,
    val updatedAt: String,
    val wind: String,
    val humidity: String,
    val pressure: String,
    val sunrise: String,
    val sunset: String,
    val openOnMap: String,
    val addNote: String,
    val editNote: String,
    val open: String,
    val delete: String,
    val save: String,
    val cancel: String,
    val close: String,
    val noteLabel: String,
    val notePlaceholder: String,
    val language: String,
    val russian: String,
    val english: String,
    val theme: String,
    val light: String,
    val dark: String,
    val about: String,
    val settingsSourcesTitle: String,
    val settingsSourcesFootnote: String,
    val openDetails: String,
    val noFavorites: String,
    val detailedInformation: String,
    val sevenDayForecast: String,
    val version: String,
    val updated: String,
    val offlineWeatherHint: String,
    val setAsHomeCity: String,
    val mapSearchPlaceholder: String,
    val mapSearchResultHint: String,
    val mapSearchNoResults: String
)

val stringsRu = AppStrings(
    searchPlaceholder = "Поиск города",
    addToFavorites = "Добавить в избранное",
    inFavorites = "В избранном",
    details = "Подробнее",
    home = "Домой",
    map = "Карта",
    favorites = "Избранное",
    settings = "Настройки",
    updatedAt = "Обновлено",
    wind = "Ветер",
    humidity = "Влажность",
    pressure = "Давление",
    sunrise = "Восход",
    sunset = "Закат",
    openOnMap = "Открыть на карте",
    addNote = "Добавить заметку",
    editNote = "Редактировать заметку",
    open = "Открыть",
    delete = "Удалить",
    save = "Сохранить",
    cancel = "Отмена",
    close = "Закрыть",
    noteLabel = "Заметка",
    notePlaceholder = "Введите заметку...",
    language = "Язык",
    russian = "Русский",
    english = "Английский",
    theme = "Тема",
    light = "Светлая",
    dark = "Тёмная",
    about = "О приложении",
    settingsSourcesTitle = "Источники данных",
    settingsSourcesFootnote = "Прогноз погоды: API Open-Meteo (forecast).\nКарта: osmdroid, тайлы OpenStreetMap.\nПоиск места по названию на карте: Open-Meteo Geocoding API.\nКоординаты городов каталога заданы в приложении и используются для запросов прогноза.",
    openDetails = "Перейти в детали",
    noFavorites = "Нет избранных городов",
    detailedInformation = "Подробная информация",
    sevenDayForecast = "7-дневный прогноз",
    version = "Версия: 1.0.0",
    updated = "Обновлено: 19.02.2026",
    offlineWeatherHint = "Нет сети — показаны данные без обновления",
    setAsHomeCity = "Сделать домашним",
    mapSearchPlaceholder = "Поиск на карте",
    mapSearchResultHint = "Нажмите «Сделать домашним», чтобы показывать погоду этого города на главном экране.",
    mapSearchNoResults = "Ничего не найдено — попробуйте другое название"
)

val stringsEn = AppStrings(
    searchPlaceholder = "Search city",
    addToFavorites = "Add to favorites",
    inFavorites = "In favorites",
    details = "Details",
    home = "Home",
    map = "Map",
    favorites = "Favorites",
    settings = "Settings",
    updatedAt = "Updated at",
    wind = "Wind",
    humidity = "Humidity",
    pressure = "Pressure",
    sunrise = "Sunrise",
    sunset = "Sunset",
    openOnMap = "Open on map",
    addNote = "Add note",
    editNote = "Edit note",
    open = "Open",
    delete = "Delete",
    save = "Save",
    cancel = "Cancel",
    close = "Close",
    noteLabel = "Note",
    notePlaceholder = "Enter note...",
    language = "Language",
    russian = "Russian",
    english = "English",
    theme = "Theme",
    light = "Light",
    dark = "Dark",
    about = "About",
    settingsSourcesTitle = "Data sources",
    settingsSourcesFootnote = "Weather forecast: Open-Meteo API (forecast).\nMap: osmdroid library, OpenStreetMap tiles.\nMap place search by name: Open-Meteo Geocoding API.\nCatalog city coordinates are embedded in the app and used for forecast requests.",
    openDetails = "Open details",
    noFavorites = "No favorite cities",
    detailedInformation = "Detailed Information",
    sevenDayForecast = "7-day forecast",
    version = "Version: 1.0.0",
    updated = "Updated: 19.02.2026",
    offlineWeatherHint = "Offline — showing cached placeholder data",
    setAsHomeCity = "Set as home city",
    mapSearchPlaceholder = "Search on map",
    mapSearchResultHint = "Tap «Set as home city» to show this city’s weather on the home screen.",
    mapSearchNoResults = "Nothing found — try a different name"
)

fun strings(language: AppLanguage): AppStrings {
    return if (language == AppLanguage.RU) stringsRu else stringsEn
}
